/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package chat;

import static java.util.Collections.list;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author a132067x
 */
public class TelaMensagem extends javax.swing.JPanel {

    /**
     * Creates new form telaMensagem
     */
    public TelaMensagem(  ) {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfTexto = new javax.swing.JTextField();
        btEnviar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        spMensagem = new javax.swing.JScrollPane();
        taMensagem = new javax.swing.JTextArea();

        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        lbTitulo.setText("Tela de Mensagem");

        taMensagem.setColumns(20);
        taMensagem.setRows(5);
        spMensagem.setViewportView(taMensagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spMensagem)
                            .addComponent(tfTexto))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btEnviar))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(lbTitulo)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTexto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btEnviar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        MensagemDAO mensagemDAO = new MensagemDAO();
        try{
          String nick = MeuMessenger.nickUsuario;
          String texto = tfTexto.getText();
          
          Mensagem mensagem = new Mensagem();
          mensagem.setDate(new java.sql.Date(new java.util.Date().getTime()));
          mensagem.setTexto(texto);
          mensagem.setNick(nick);
          
          mensagemDAO.Inserir(mensagem);
          this.atualizarMensagensTrocadas();
        }
        
        catch(Exception e){
            String alerta = "Não foi possivel enviar a sua mensagem.\nProblema com a conexão";
            JOptionPane.showMessageDialog(null, alerta);
        }
        tfTexto.setText("");
    }//GEN-LAST:event_btEnviarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        this.atualizarMensagensTrocadas();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void atualizarMensagensTrocadas(){
        MensagemDAO mensagemDAO = new MensagemDAO();
        try{
            
           List mensagens = mensagemDAO.ObterMensagens();
           
           String corpoMensagens="";
           
           Iterator i = mensagens.iterator();
           
           while(i.hasNext()){
               Mensagem msg = (Mensagem) i.next();
                corpoMensagens += "\n" + msg.getNick() + ": " + msg.getTexto();
           }
           
           taMensagem.setText(corpoMensagens);
        }
        catch(Exception e){
            String alerta = "Não foi possivel atualizar.\n Problema com a conexão";
            JOptionPane.showMessageDialog(null, alerta);
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btEnviar;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JScrollPane spMensagem;
    private javax.swing.JTextArea taMensagem;
    private javax.swing.JTextField tfTexto;
    // End of variables declaration//GEN-END:variables
}
