/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package chat;

import static java.util.Collections.list;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author a132067x
 */
public class TelaMensagem extends javax.swing.JPanel {

    /**
     * Creates new form telaMensagem
     */
    public TelaMensagem(  ) {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfTexto = new javax.swing.JTextField();
        btEnviar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        lbTitulo = new javax.swing.JLabel();
        spMensagem = new javax.swing.JScrollPane();
        taMensagem = new javax.swing.JTextArea();
        jbNewUser = new javax.swing.JButton();

        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        lbTitulo.setText("Tela de Mensagem");

        taMensagem.setEditable(false);
        taMensagem.setColumns(20);
        taMensagem.setRows(5);
        spMensagem.setViewportView(taMensagem);

        jbNewUser.setText("NovoUsuario");
        jbNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                            .addComponent(tfTexto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbNewUser, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(lbTitulo)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(spMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNewUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        MensagemDAO mensagemDAO = new MensagemDAO();
        try{
          String nick = MeuMessenger.usuario.getLogin();
          String texto = tfTexto.getText();
          
          Mensagem mensagem = new Mensagem();
          mensagem.setDate(new java.sql.Date(new java.util.Date().getTime()));
          mensagem.setTexto(texto);
          mensagem.setNick(nick);
          
          mensagemDAO.Inserir(mensagem);
          this.atualizarMensagensTrocadas();
        }
        
        catch(Exception e){
            String alerta = "Não foi possivel enviar a sua mensagem.\nProblema com a conexão";
            JOptionPane.showMessageDialog(null, alerta);
        }
        tfTexto.setText("");
    }//GEN-LAST:event_btEnviarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        this.atualizarMensagensTrocadas();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void jbNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewUserActionPerformed
        JPanel newuser = new NovoUsuario();
        JScrollPane jsc = new JScrollPane(newuser, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        //this.resize(395, 310);
       // MeuMessenger.setContentPane();
        //newuser.show();
        this.revalidate();
        this.repaint();
        
    }//GEN-LAST:event_jbNewUserActionPerformed

    private void atualizarMensagensTrocadas(){
        MensagemDAO mensagemDAO = new MensagemDAO();
        try{
            
           List mensagens = mensagemDAO.ObterMensagens();
           
           String corpoMensagens="";
           
           Iterator i = mensagens.iterator();
           
           while(i.hasNext()){
               Mensagem msg = (Mensagem) i.next();
                corpoMensagens += "\n" + msg.getNick() + ": " + msg.getTexto();
           }
           
           taMensagem.setText(corpoMensagens);
        }
        catch(Exception e){
            String alerta = "Não foi possivel atualizar.\n Problema com a conexão";
            JOptionPane.showMessageDialog(null, alerta);
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btEnviar;
    private javax.swing.JButton jbNewUser;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JScrollPane spMensagem;
    private javax.swing.JTextArea taMensagem;
    private javax.swing.JTextField tfTexto;
    // End of variables declaration//GEN-END:variables
}
